### ISSUE TITLE
lsp-metals-doctor-run is not working

### ISSUE THREAD

**Issue by chessman** [emacs-lsp/lsp-metals#23]
**Describe the bug**
`lsp-metals-doctor-run` command is not working.

**To Reproduce**
Run lsp-metals-doctor-run in a scala project. It shows a warning instead of a doctor table.

**Logs**
```
Warning (lsp-mode): Unknown notification: metals/executeClientCommand
```

**Comment by kurnevsky** [comment]
@chessman which version of lsp-metals do you use? It works fine for me with the latest master.

**Comment by chessman** [comment]
I double checked my configuration and it's fixed now. The problem was that I had lsp-scala package installed.
