### ISSUE TITLE
Treeview Never Gets Information

### ISSUE THREAD

**Issue by allenjohnashton** [emacs-lsp/lsp-metals#26]
Treeview never launches, if I manually launch treeview I see "Waiting for Metals Treeview information...".

The tab not launching until it gets information seems to be WAI but I'm not sure why it never get's information.  I set lsp-metals-treeview-logging but don't see anything in *lsp-log* that appears relevant to me.

How do I figure out what's going on?

**Comment by kurnevsky** [comment]
Could you check whether this commit https://github.com/emacs-lsp/lsp-metals/commit/8f8471ca1b2a3d54bafce8949e6b13c9567d0405 fixes it for you?
