### ISSUE TITLE
Documentation request: how to add a DAP-configuration for Scala? 

### ISSUE THREAD

**Issue by endrebak** [emacs-lsp/lsp-metals#29]
Hi and thanks for this package.

My problem is that I cannot get the debugger to work with this package. I have tried with both spacemacs and doom, but every time I try to start the debugger (`M-x dap-debug`) it asks me for a configuration template. Do you have a suggested template for Scala (like the ones found at https://emacs-lsp.github.io/dap-mode/page/configuration/)?

**Comment by endrebak** [comment]
Got it working. This wasn't relevant. Sorry.

**Comment by snippins** [comment]
@endrebak I couldn't figure it out myself, how did you do it?

**Comment by endrebak** [comment]
Create an object that extends App. Then a run|debug lens should show above the object definition. This wasn’t/isn’t documented anywhere AFAICS. It is just magic.

Don’t remember what the rest of my settings were like. But I am using the Scala layer in Doom. And I followed the installation instructions for enacts-metals.

**Comment by snippins** [comment]
@endrebak I have already used the lens, but this doesn't cover the case where I need to pass arguments :((.

**Comment by endrebak** [comment]
Yeah, I might start to use IntelliJ when I need to debug stuff :/
