### ISSUE TITLE
Symbol’s function definition is void: treemacs-define-doubleclick-action

### ISSUE THREAD

**Issue by marcsaegesser** [emacs-lsp/lsp-metals#38]
**Describe the bug**
After updating to the latest versions of package I get the following error when I start Emacs or try to open a Scala project.
Symbol’s function definition is void: treemacs-define-doubleclick-action

I think the problem was caused by a recent change to treemacs. As a hack I added `(require 'treemacs-mouse-interface)` to lsp-metals-treeview.el and the problem went away.

**To Reproduce**
Use the most recent packages from elpa and start emacs.

**Expected behavior**
Start without errors.

**Comment by gagbo** [comment]
I just added `(autoload 'treemacs-define-doubleclick-action "treemacs-mouse-interface" nil nil)` to my `init.el` and it solved it as well, as far as I understand.

I went for this because :
- that means I don't have to edit lsp-metals source directly, and 
- The autoload means I don't eagerly load the code each time

**Comment by marcsaegesser** [comment]
@gagbo Thanks for that. Now I've learned something new today!

**Comment by kurnevsky** [comment]
Looks like it should be reported to treemacs. We don't use this function directly, so probably `treemacs-extensions` should require `treemacs-mouse-interface`.

**Comment by kurnevsky** [comment]
Caused by https://github.com/Alexander-Miller/treemacs/issues/464

**Comment by Alexander-Miller** [comment]
> treemacs-extensions should require treemacs-mouse-interface.

That's been pushed now.

**Comment by marcsaegesser** [comment]
Things seem good now. Thank you, all.

**Comment by wyuenho** [comment]
It looks like this issue is back

**Comment by gagbo** [comment]
It shouldn't be the case. The root cause of this issue was a missing autoload cookie, and it’s been [fixed in treemacs 3 years ago](https://github.com/Alexander-Miller/treemacs/blame/master/src/elisp/treemacs-mouse-interface.el#L197)

**Comment by wyuenho** [comment]
Looks like Alexander-Miller/treemacs@2f77c9828116767f1be5cfdd3f82d2bed7ceea93 has broken it again

**Comment by Alexander-Miller** [comment]
So anyway, treemacs has a new feature that lets you define double-click actions for your extensions now :neutral_face:.
