### ISSUE TITLE
Company completion not working

### ISSUE THREAD

**Issue by ashkan-leo** [emacs-lsp/lsp-metals#39]
**Describe the bug**
I am using Doom Emacs, and company completion does not work for me when editing Scala code.
Other functionalities like goto definition, type inference, etc. seem to work fine.

**To Reproduce**
This happens with multiple projects. I have attached a toy project too.
[awesome-zio-bak.zip](https://github.com/emacs-lsp/lsp-metals/files/5799260/awesome-zio-bak.zip)

**Expected behavior**
The company completion should work in Scala projects.

**Screenshots**

**Logs**
Please include the debug stack trace (if there is an error) and the content of Messages buffer with `lsp-print-io` set to t in case the bug is related to client->server communication.

**Comment by jackcviers** [comment]
More interesting news on this bug:

Company completion works perfectly if the project has scalaVersion:="2.13.3" or below, but with 2.13.5 it fails, even though lsp-metals-doctor-run shows everything should work just fine.

Top-level compeltions of object/class names are fine. It is method level completion that fails. This is, obviously, with metals Tungsten.

Did something change in the protocol between 2.13.5 and 2.13.3?

Also, I have tried with both company-lsp and without. company-lsp is deprecated in the latest lsp-mode, and you can just use company.

**Comment by kurnevsky** [comment]
@ashkan-leo @jackcviers is it still an issue? Just checked attached project and completion works fine for me there.
