### ISSUE TITLE
dap-ui-repl just returns the message `an implementation is missing`

### ISSUE THREAD

**Issue by brakende** [emacs-lsp/lsp-metals#43]
**Describe the bug**
When I start a `dap-ui-repl` and want to evalutate an expression in the REPL I get the message `an implementation is missing`.

**To Reproduce**
Steps to reproduce the behavior(sample project + file which can be used to reproduce the issue with.)

Create a simple Main object that extends app. Set a breakpoint. Start the debugging. Call `M-x dap-ui-repl`. Type 1<RET>.

**Expected behavior**
Should evaluate to 1 instead of showing `an implementation is missing`

**Screenshots**

**Comment by kurnevsky** [comment]
It means it's not implemented on metals side. So not much we can do here.

**Comment by ckipp01** [comment]
> It means it's not implemented on metals side. So not much we can do here.

Can you provide some more info about what is actually missing on the Metals side?

**Comment by kurnevsky** [comment]
This one: https://github.com/scalameta/metals-feature-requests/issues/83
