### ISSUE TITLE
Starting a debug session with the ui 

### ISSUE THREAD

**Issue by Jeronimo-GL** [emacs-lsp/lsp-metals#49]
When I try start a debug session using the ui menu instead of the lens I get the following error:
`Error running timer: (wrong-type-argument stringp nil)`

I suspect that the problem is related with my template:

```
(dap-register-debug-template
  "Analyzer"
  (list :type "scala"
        :request "debug"
        :name "Analyzer"
        :projectName "Analyzer"
        :mainClass "analyzer.Main"
        :args "blah bl;ah"
        :vmArgs ""))
```

Is there anything wrong with the template? Where can I find a template that works? I can't find any.

**Comment by yyoncho** [comment]
Templates does not work, I will try to fix them. Also I will try to fix https://github.com/emacs-lsp/lsp-metals/issues/41

**Comment by yyoncho** [comment]
PR #51
