### ISSUE TITLE
Question : lsp hint faces ?

### ISSUE THREAD

**Issue by gagbo** [emacs-lsp/lsp-metals#55]
Hello,

Sorry for the dumb question (I don't think there's a gitter specifically for lsp-metals, but I've been wrong before), but I'm using the `lsp-metals-show-inferred-type` variables, and I thought that the hints would use the `lsp-details-face` but instead I think I have a face that resembles `comment`.

Do you know which face is actually used for those inline hints ? How should I find out about these in general ?

Thanks for the package,

Gerry

**Comment by kurnevsky** [comment]
We just hardcoded it for all metals decorations as comment because metals didn't provide overlay type, only colors: https://github.com/emacs-lsp/lsp-metals/blob/9f82ebee48d32cd7bbc3e64b84d1ef5b0926195b/lsp-metals.el#L445

Do they look different in vscode?

**Comment by gagbo** [comment]
No no I’m okay with that, it’s just that I prefer those to be different from comments, so I was wondering which face to change.

Would it be possible to put a custom there, or use the `lsp-details-face` It seems to be the [one to use](https://emacs-lsp.github.io/lsp-mode/page/settings/mode/#lsp-details-face) ?

**Comment by gagbo** [comment]
I think it’s easier to provide a patch to show what I mean
