### ISSUE TITLE
the following functions are not known to be defined: -compose,     -rpartial, -andfn, -not

### ISSUE THREAD

**Issue by elefthei** [emacs-lsp/lsp-metals#62]
**Describe the bug**
```
Warning (bytecomp): the following functions are not known to be defined: -compose,
    -rpartial, -andfn, -not
```

**To Reproduce**
lsp-metals with use-package like this
```
(use-package lsp-metals
  :ensure t
  :custom
  ;; Metals claims to support range formatting by default but it supports range
  ;; formatting of multiline strings only. You might want to disable it so that
  ;; emacs can use indentation provided by scala-mode.
  (lsp-metals-server-args '("-J-Dmetals.allow-multiline-string-formatting=off"))
  :hook (scala-mode . lsp))
```

**Expected behavior**
lsp-metals to install and run without errors. Also when I try to 
M-x lsp-install-server the same error about `-compose` appears.

**Screenshots**

**Logs**
Please include the debug stack trace (if there is an error) and the content of Messages buffer with `lsp-print-io` set to t in case the bug is related to client->server communication.

**Comment by yyoncho** [comment]
reinstall `dash` package.

**Comment by elefthei** [comment]
That did it, thanks!
