### ISSUE TITLE
Can't install server (signature expired)

### ISSUE THREAD

**Issue by vitalydolgov** [emacs-lsp/lsp-metals#65]
`M-x lsp-install-server` on Emacs 27.2 gives the following error:
```
LSP :: Server metals install process failed with the following error message: (error Failed to verify GPG signature: Signature made by expired key CD1B9D8DC84ECA56 Alexandre Archambault (Travis CI coursier) <alexandre.archambault+traviscicoursier@gmail.com>).
```
Could you please check what's happening?

**Comment by kurnevsky** [comment]
There were changes in the coursier installation process, see https://github.com/coursier/coursier/issues/2346

**Comment by EdwardIII** [comment]
Is there a way we can work around this temporarily? Pinning an older version or something like this?

**Comment by kurnevsky** [comment]
There is a setting in lsp-mode that can be disabled: https://github.com/emacs-lsp/lsp-mode/blob/fbfaa80095a82f7473cb7e45fe73b32ecc1900ae/lsp-mode.el#L7328

**Comment by arigoldx** [comment]
Say, @kurnevsky I see that there's a fix to the coursier urls and am assuming that that should fix this issue (thanks!) but that's for `lsp-metals` version 1.3 and I'm only seeing 1.2 when I `list-packages`.

Maybe 1.3 is yet-to-be-released?

**Comment by kurnevsky** [comment]
Yeah, long time since last release. Do you use melpa stable on purpose?

**Comment by arigoldx** [comment]
> Do you use melpa stable on purpose?

_nope_ -- I probably just followed some instructions that said to add it. I take it life would be better if I switched? 😉 Happy to!

**Comment by arigoldx** [comment]
I must have found a way around this because I ran across this again and, after some [reading](https://www.reddit.com/r/emacs/comments/etikbz/speaking_as_a_package_maintainer_please_do_not/) am convinced that I need to stop using melpa stable buuuuut can't easily find out how to "switch".

I changed the priority in my `init.el`:

```
(setq
 package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                    ("org" . "http://orgmode.org/elpa/")
                    ("melpa" . "https://melpa.org/packages/")
                    ("melpa-stable" . "http://stable.melpa.org/packages/"))
 package-archive-priorities '(("melpa" . 5)
                              ("melpa-stable" . 0)))
```

but no dice. Any ideas?

I figured I'd post in case folks have a recommended way to use lsp-metals.

Still :eyes: and will post if/when I get this locked in.
