### ISSUE TITLE
Cannot install Metals 0.11.3+

### ISSUE THREAD

**Issue by nigredo-tori** [emacs-lsp/lsp-metals#69]
**Describe the bug**

`lsp-install-server` installs Metals 0.11.2, even though the current version is 0.11.4 (or 0.11.5 if you go by [Maven Central](https://repo1.maven.org/maven2/org/scalameta/metals_2.13/))

**To Reproduce**

`lsp-install-server`, choose `metals`, wait until the end of the installation. Run `path/to/metals --version`, and observe that it's 0.11.2.

**Expected behavior**

`lsp-install-server` should install the latest released Metals version.

**Analysis**

The issue seems to be that Metals has switched to Scala 2.13, whereas this project has 2.12 [hardcoded](https://github.com/emacs-lsp/lsp-metals/blob/b7f77de69431786c54e9a57845e4f2d75fbee053/lsp-metals.el#L278).

**Comment by TimWSpence** [comment]
@nigredo-tori thank you for diagnozing this!! I thought I was going crazy 😅
