### ISSUE TITLE
Hovering over output in worksheet not working

### ISSUE THREAD

**Issue by barshirtcliff** [emacs-lsp/lsp-metals#71]
**Describe the bug**
According to [this page](https://scalameta.org/metals/docs/editors/emacs/) I should be able to hover over the comment-output generated in a worksheet to see the complete output.  This works in other editors, such as IntelliJ and Code.  In emacs, however, nothing happens.

**To Reproduce**

create a worksheet named `foo.worksheet.sc` anywhere.
add a line:
`val longString = "thisisalongstring" * 10`
save the file.

**Expected behavior**
hovering over the comment should reveal the complete string.  but nothing shows up.

**Screenshots**
Here's the test output.  No new output appears in the `*lsp-log*` buffer during hover.
<img width="2183" alt="Screen Shot 2022-05-09 at 10 12 02 AM" src="https://user-images.githubusercontent.com/81589750/167462098-ac993008-dcb7-4cea-babb-4f78324a59f7.png">

**Comment by barshirtcliff** [comment]
This is a more complete representation of a bug identified [previously](https://github.com/emacs-lsp/lsp-metals/issues/52).

**Comment by kurnevsky** [comment]
Try to hover over the string itself, not over commented part. Emacs doesn't support  help messages over added overlays.

**Comment by kurnevsky** [comment]
Actually it can be done using text property instead of overlay property.
