### ISSUE TITLE
Running unit test

### ISSUE THREAD

**Issue by arussel** [emacs-lsp/lsp-metals#75]
**Describe the bug**
Not a bug, I just can't find a way to run a method of a unit test. I have the run test/debug test on the class, but nothing on each unit test method. Is it at all possible or missing currently ?

**Comment by LaurenceWarne** [comment]
Related is https://github.com/scalameta/metals-feature-requests/issues/216, so not atm but maybe soon :wink:.

**Comment by LaurenceWarne** [comment]
As of [0.11.10](https://scalameta.org/metals/blog/2023/01/02/aluminium), you should see lenses for individual tests for the most common test libraries.
