### ISSUE TITLE
Poor contrast in treeview in light mode

### ISSUE THREAD

**Issue by cpitclaudel** [emacs-lsp/lsp-metals#96]
**Describe the bug**
With `frame-background-mode` set to `light` and a light theme (e.g. tango), metals uses white icons on white background in `lsp-metals-treeview`, even with `lsp-metals-treeview-theme` set to `Metals-dark`.

**Screenshots**

![Screenshot from 2023-06-11 12-51-57](https://github.com/emacs-lsp/lsp-metals/assets/8181630/4f3349aa-56d2-4e54-8ef0-0eec93ccd752)

![Screenshot from 2023-06-11 12-53-00](https://github.com/emacs-lsp/lsp-metals/assets/8181630/91d89c29-47ed-485f-80c0-7ad35c40d5c1)

**Comment by kurnevsky** [comment]
Fixed by https://github.com/emacs-lsp/lsp-metals/commit/c1d90f64abdfd1af52f041ed420ab772dc8abc73
